'use strict';
console.log('hello, world');
const h1First = document.querySelector('h1');
console.dir(h1First);
const idExplanation = document.querySelector('#explanation');
console.dir(idExplanation);
const classHint = document.querySelector('.hint');
console.dir(classHint);
const pAll = document.querySelectorAll('p');
console.dir(pAll);
const classExampleLink = document.querySelectorAll('.example-link');
console.dir(classExampleLink);
